import requests
import bs4
from urllib.parse import urlparse, quote
from pathlib import Path
from pprint import pprint
from fastcore.all import *


@call_parse
def make_index():
    initial_response = requests.get("https://help.dyalog.com")
    version = urlparse(initial_response.url).path.strip("/")
    symbols_url = f"https://help.dyalog.com/{version}/Content/Language/Introduction/Language%20Elements.htm"
    res = requests.get(symbols_url)
    html = bs4.BeautifulSoup(str(res.content, "utf-8"), features="lxml")
    tables = html.find_all("table")
    function_table = tables[0]
    operator_table = tables[1]
    
    def table2dict(table):
        elements = table.find_all("a")
        d = {ele.text: f"https://help.dyalog.com/{version}/index.htm#Language/{quote(ele['href'].lstrip('./'))}" for ele in elements}
        return d
    
    functions = table2dict(function_table)
    operators = table2dict(operator_table)
    syms = dict(primitive_functions=functions, primitive_operators=operators)
    lib_path = Path("nbdev_apl")
    lib_path.mkdir(exist_ok=True)
    with (lib_path/"_modidx.py").open('w') as f:
        f.write("# Autogenerated by apl_mk_index.py\n\nd = ")
        d = dict(syms = syms, settings={'lib_path':lib_path.name})
        pprint(d, f, width=160, indent=2, compact=True)